[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/test"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Environment variables for Railway
[env]
DATABASE_PATH = "/app/data/app.db"
RAILWAY_ENVIRONMENT = "production"

# Note: Volumes are now created and attached through Railway dashboard
# The volume should be mounted to /app/data in the Railway dashboard 